version: "3"
services:
  golang-jwt-project:
    build:
      context: ./
    image: golang-jwt-project:latest
    container_name: golang-jwt-project
    environment:
      PORT: "8080"
      MONGODB_URL: "mongodb://mongodb:27017/go-auth"
    restart: always
    depends_on:
      - mongodb
    ports:
    - "8080:8080"
    - "9090:9090"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: go-auth
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: